import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import ReactContextProvider from "@/lib/recoil/RecoilContextProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Feedback flow - Collect feedback and make your dream application flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="max-w-4xl mx-auto">
      <body className={inter.className}>
        <ReactContextProvider>
          {children}
        </ReactContextProvider>
        </body>
    </html>
  );
}
